jobs:

  contexts-demo:
    name: Contexts Demo
    description:
      This job demonstrates the use of contexts and the inheritance 
      of `task-defaults` e.g. from the top level context to its 
      subcontexts. 

    context: 

      task-defaults: 
        traits:
          linux: true
          bash: true
        environment-variables:
           STAR: Sun
           PLANET: Earth
           MOON: Moon
        
      tasks: 

        earth-check:
          name: Earth Check
          scripts: 
            main:
              body: |
                test $STAR = 'Sun'  \
                && test $PLANET = 'Earth' \
                && test $MOON = 'Moon' 

      subcontexts: 

        jupiter:

          name: Jupiter 

          task-defaults: 
            environment-variables:
              PLANET: Jupiter

          tasks: 
            jupiter-check:
              name: Jupiter Check
              scripts: 
                main:
                  body: |
                    test $STAR = 'Sun'  \
                    && test $PLANET = 'Jupiter'

          subcontexts: 

            io:

              name: Io

              task-defaults: 
                environment-variables:
                  MOON: Io

              tasks: 
                io-check:
                  name: Io Check
                  scripts: 
                    main:
                      body: |
                        test $STAR = 'Sun'  \
                        && test $PLANET = 'Jupiter' \
                        && test $MOON = 'Io' 

