jobs:

  environment_variables:
    name: Environment Variables Demo
    description: |
      This job Demonstrates the usage of the `environment_variables` and
      the `template_environment_variables` directive.

      The _Set and Show_ subcontext demonstrates inheritance and runs
      some basic tests.

      The _Substitution_ subcontext demonstrates the usage and tests
      the `template_environment_variables` directive.

    context:

      task_defaults:
        environment_variables:
          CI_TASK_DEFAULTS: "Inherited!"
          SOME_DEFAULT: "X"
          THE_ANSWER: 42
        traits:
          Bash: true


      subcontexts:

        set_and_show:

          name: Set and Show

          tasks:

            show:
              name: Set and Show Environment Variables
              scripts:
                show:
                  body: |
                    set -eux
                    env | sort

            test-context-inheritance:
              description: |
                Test if an env-var setting is inherited from the super-context.
              scripts:
                test-inheritance:
                  body: |
                    set -eux
                    env | sort
                    test ${SOME_DEFAULT} == "X"

            test-script-overrides:
              description: |
                Test if an inherited env-var setting is shadowed
                by a script setting.
              scripts:
                test-script-overrides:
                  environment_variables:
                    SOME_DEFAULT: "Y"
                  body: |
                    set -eux
                    env | sort
                    test ${SOME_DEFAULT} == "Y"


        substitution:

          name: Substitution

          tasks:

            enabled-substitution:
              name: "Enabled Substitution"
              script_defaults:
              scripts:
                substitute_ci_var:
                  environment_variables:
                    THE_SUBSTITUTED_ANSWER: "{{THE_ANSWER}}"
                  template_environment_variables: true
                  body: |
                    set -eux
                    test "${THE_SUBSTITUTED_ANSWER}" = 42

            recursive-substitution:
              name: "Recursive Substitution"
              ports:
                XVNC_PORT:
                  inet_address: "localhost"
                  min: 5900
                  max: 5999
              scripts:
                substitute_ci_var:
                  environment_variables:
                    T1: "{{T2}}"
                    T2: "{{T3}}"
                    T3: 7
                    P1: "{{XVNC_PORT}}"
                    P2: "{{P1}}"
                    P3: "{{P2}}"
                  template_environment_variables: true
                  body: |
                    set -eux
                    test "${T1}" = 7
                    test "${P3}" = "${XVNC_PORT}"
                    test "${P3}_${T1}" = "${XVNC_PORT}_7"

            disabled-substitution:
              name: "Disabled Substitution"
              scripts:
                substitute_ci_var:
                  template_environment_variables: false
                  environment_variables:
                    THE_SUBSTITUTED_ANSWER: "{{THE_ANSWER}}"
                  body: |
                    set -eux
                    test "${THE_SUBSTITUTED_ANSWER}" != 42
