jobs:

  exclusive-executor-resource:
    name: Exclusive Executor Resource
    description:
      This job tests the `exclusive-executor-resource` directive of scripts.

      The `exclusive-executor-resource` directive ensures that at any given
      time only one script with a particular value is executing for a
      particular executor.


    context:

      script_defaults:

        exclusive-executor-resource: "/tmp/exclusive-executor-resource.txt"

        body: |
          set -eux
          START_VAL=$(echo $RANDOM | shasum | cut -d ' ' -f 1)
          echo "$START_VAL" > /tmp/exclusive-executor-resource.txt
          sleep $((RANDOM % 5 + 1))
          FILE_VAL=$(cat /tmp/exclusive-executor-resource.txt)
          test $FILE_VAL = $START_VAL


      task_defaults:

        traits:
          Bash: true

      tasks:

        task1:
          scripts:
            s1: {}
            s2: {}
            s3: {}
            s4: {}
            s5: {}

        task2:
          scripts:
            s1: {}
            s2: {}
            s3: {}
            s4: {}
            s5: {}
