jobs:

  submodules:
    name: Submodule Demo
    description: |
      This job demonstrates  the usage of the `git-options`/`submodule`
      specification.  It also checks some properties fails if they 
      the feature would not work as expected. 

    context:

      task-defaults:
        eager-trials: 1
        max-auto-trials: 2

        traits:
          linux: true
          bash: true

        git-options: 
          submodules: 
            clone: True 
            timeout: 30

      tasks: 

        submodule-exists:
          name: Verify that file in submodule does exist
          scripts: 
            main: 
              body: test -f submodule/README.mkd

        ls-dir:
          name: List submodule directory
          scripts: 
            main: 
              body: 
                ls -lah submodule 

        verify-commit:
          name: Verify proper commit in submodule directory 
          scripts: 
            main: 
              body: cd submodule && test $(git log -n 1 --pretty='%H') == cec555fbe7b525c61c53f5233e4af4d4325732ea

        verify-no-clone:
          name: Verify that file in submodule does not exist if clone is False
          git-options: 
            submodules: 
              clone: False
          scripts: 
            main: 
              body: test ! -f submodule/README.mkd

