jobs:

  submodules:
    name: Submodule Demo
    description: |
      This job demonstrates  the usage of the `git-options`/`submodule`
      specification.  It also checks some properties and fails if the
      feature does not work as expected.

    context:

      task-defaults:
        eager-trials: 1
        max-auto-trials: 2

        traits:
          bash: true

        git-options:
          submodules:
            clone: True
            timeout: 30

      tasks:

        submodule-exists:
          name: Verify that file in submodule does exist
          scripts:
            main:
              body: test -f submodule/README.mkd

        ls-dir:
          name: List submodule directory
          scripts:
            main:
              body:
                ls -lah submodule

        verify-commit:
          name: Verify proper commit in submodule directory
          scripts:
            main:
              body: cd submodule && test $(git log -n 1 --pretty='%H') == 3b69510478ea1d9858e949bdd196db5629aeb1da

        test-clone-false:
          name: Verify that file in submodule does not exist if clone is False
          git-options:
            submodules:
              clone: False
          scripts:
            main:
              body: test ! -f submodule/README.mkd

        test-include-match:
          name: Verify that file in submodule does not exist if clone is False
          git-options:
            submodules:
              clone:
                include-match: submodule
          scripts:
            main:
              body: test -f submodule/README.mkd

        test-exclude-match:
          name: Verify that file in submodule does not exist if clone is False
          git-options:
            submodules:
              clone:
                exclude-match: submodule|or-whatever
          scripts:
            main:
              body: test ! -f submodule/README.mkd

