jobs:

  job-prerequisite:

    name: Jobs - Dependencies and Triggers - Prerequisite
    description: |
      This one serves as a prerequisite to "job-depends".
      Additionally it will be automatically triggered if a branch matching the
      regular expression /^trigger-prerequisite$/ is updated.

    run_on:
    - type: branch
      include_match: ^trigger-prerequisite$

    context:

      tasks:

        sleep:
          name: Sleep

          traits:
            Bash: true

          scripts:
            main:
              body: sleep 3 && echo "done sleeping"


  job-dependent:

    name: Jobs - Dependencies and Triggers - Dependent
    description: |
      This demo can only be started if the "job-prerequisite" has passed. There
      is also a corresponding trigger defined for the sake of demonstration.

    depends_on:
    - type: job
      job: job-prerequisite
      states: [passed]

    run_on:
    - type: job
      job: job-prerequisite
      states: [passed]

    context:

      tasks:

        sleep:

          name: Sleep

          traits:
            Bash: true

          scripts:
            main:
              body: sleep 3 && echo "done sleeping"

  job-submodule-dependent:

    name: Jobs - Dependencies and Triggers - Submodule-Dependent
    description: |
      This demo can only be started if the "job-prerequisite" in the submodule
      `submodule` has passed.

    depends_on:
    - type: job
      job: job-prerequisite
      submodule: ['submodule']
      states: [passed]

    run_on:
    - type: branch
      include_match: ^.*$

    context:

      tasks:

        sleep:

          name: Sleep

          traits:
            Bash: true

          scripts:
            main:
              body: sleep 3 && echo "done sleeping"


