jobs: 

  ports:
    name: Ports Demo
    description: |
      This job demonstrates the usage of the `ports` directive.  The
      output of `env | sort` shows the assigned port as the value of the given
      name.

    context:

      task-defaults:
        traits:
          linux: true
          bash: true
        environment-variables:
          CI_TASK_DEFAULTS: "Inherited!"

      tasks: 

        ports:

          name: Ports Demo 

          description: This task demonstrates the `ports` property. 

          ports: 
            XVNC_PORT: 
              inet_address: "localhost"
              min: 5900
              max: 5999

          scripts:
            list:
              body: env | sort  
            test:
              body: echo ${XVNC_PORT? "XVNC_PORT is not set!"}
