jobs:

  result:
    name: Result Demo
    description: |
      This job creates the specially treated `result.json` file with
      `value`, and `summary` properties.  It also attaches the `result.json` by
      the `trial_attachments` directive.

    context:

      tasks:

        result:

          name: Result Embedding Demo

          description: >
            This tasks creates a result.json file and demonstrates the embedding of
            the contents as the result in script, and task.  The result property is
            available in the job if and only if it contains exactly this task
            and no further.

          traits:
            Bash: true

          trial_attachments:
            result_file:
              content_type: application/json
              include_match: ^result\.json$

          scripts:
            main:
              body: ./bin/create-result-json
