jobs:

  dispatch-storm-delay:

    name: Dispatch-Storm Delay Demo
    description: |
      This job demonstrates the 'dispatch-storm-delay-duration' feature.

    context:

      task_defaults:
        eager_trials: 2
        max_trials: 2
        dispatch-storm-delay-duration: 20 Seconds
        traits:
          Bash: true
        scripts:
          main:
            body: sleep 30

      tasks:
        t1: {}
        t2: {}
