jobs:

  timeout:
    name: Timeout Demo
    description: |
      This job has one task which will fail because it times out
      and one that will pass.

    context:

      tasks:

        pass:

          name: Pass Timeout

          scripts:
            main:
              timeout: 5 Seconds
              body: sleep 1 && exit 0
            after-main:
              start_when:
                - script: main
              body: exit 0

        fail:

          name: Fail Timeout

          description: |
            We sleep much longer than the timeout allows. Cider-CI will terminate the
            script with a appropriate method available for the given operating system.

          trial_attachments:
            logs:
              content_type: text/plain
              include_match: ^log\.txt$

          scripts:
            main:
              timeout: 5 Seconds
              body: |
                #!/usr/bin/env bash
                echo "MY PID $$" >> log.txt
                sleep 15 && exit 0
            after-main:
              start_when:
                - script: main
              body: exit 0

      task_defaults:
        traits:
          Bash: true
